### ISSUE TITLE
REGR: sindex is broken after pickling

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1746]
When we moved `sindex` to `GeometryArray`, we broke pickling. Currently if you load a pickled gdf, `sindex` raises `AttributeError: 'GeometryArray' object has no attribute '_sindex'`.

```py
import geopandas
import pandas

df = geopandas.read_file(geopandas.datasets.get_path('nybb'))
df.to_pickle('tst.pkl')

pandas.read_pickle('tst.pkl').sindex
```
```py

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-b2cfd76702ae> in <module>
----> 1 pandas.read_pickle('tst.pkl').sindex

/opt/miniconda3/envs/geo_dev/lib/python3.7/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5137             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5138                 return self[name]
-> 5139             return object.__getattribute__(self, name)
   5140 
   5141     def __setattr__(self, name: str, value) -> None:

~/Git/geopandas/martinfleis/geopandas/base.py in sindex(self)
    963     @property
    964     def sindex(self):
--> 965         return self.geometry.values.sindex
    966 
    967     @property

~/Git/geopandas/martinfleis/geopandas/array.py in sindex(self)
    293     @property
    294     def sindex(self):
--> 295         if self._sindex is None:
    296             self._sindex = _get_sindex_class()(self.data)
    297         return self._sindex

AttributeError: 'GeometryArray' object has no attribute '_sindex'
```

I think we need some machinery here as we have for CRS: https://github.com/geopandas/geopandas/blob/1ef924270e950c6e8862335c42ace8d90e5cb3db/geopandas/array.py#L420-L436

There is one related issue with the pickling of `pygeos.STRtree` which currently raises `TypeError: can't pickle pygeos.lib.STRtree objects` so that may need to be resolved before we can properly pickle gdf. 

Anyway, even if sindex will not be pickled, geodataframe read from pickle should be able to build it, which fail atm.

Works in 0.8.1.
