### PR TITLE
REGR: fix pickle issues

### LINKED ISSUE #1745: REGR: pickling shapely-backed gdf raises TypeError
If you try to pickle geodataframe without pygeos, it raises a `TypeError`. I am not sure why since the condition in `array.py` should not use the line which errors.

```python
import geopandas

geopandas.options.use_pygeos = False
df = geopandas.read_file(geopandas.datasets.get_path('nybb'))
df.to_pickle('tst.pkl')
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-a48b53e8f4f1> in <module>
----> 1 df.to_pickle('tst.pkl')

/opt/miniconda3/envs/geo_dev/lib/python3.7/site-packages/pandas/core/generic.py in to_pickle(self, path, compression, protocol)
   2674         from pandas.io.pickle import to_pickle
   2675 
-> 2676         to_pickle(self, path, compression=compression, protocol=protocol)
   2677 
   2678     def to_clipboard(

/opt/miniconda3/envs/geo_dev/lib/python3.7/site-packages/pandas/io/pickle.py in to_pickle(obj, filepath_or_buffer, compression, protocol)
     85         protocol = pickle.HIGHEST_PROTOCOL
     86     try:
---> 87         f.write(pickle.dumps(obj, protocol=protocol))
     88     finally:
     89         f.close()

~/Git/geopandas/martinfleis/geopandas/array.py in __getstate__(self)
    421 
    422         def __getstate__(self):
--> 423             return (pygeos.to_wkb(self.data), self._crs)
    424 
    425         def __setstate__(self, state):

/opt/miniconda3/envs/geo_dev/lib/python3.7/site-packages/pygeos/io.py in to_wkb(geometry, hex, output_dimension, byte_order, include_srid, **kwargs)
    156         np.intc(byte_order),
    157         np.bool(include_srid),
--> 158         **kwargs,
    159     )
    160 

TypeError: One of the arguments is of incorrect type. Please provide only Geometry objects.
```

### LINKED ISSUE #1746: REGR: sindex is broken after pickling
When we moved `sindex` to `GeometryArray`, we broke pickling. Currently if you load a pickled gdf, `sindex` raises `AttributeError: 'GeometryArray' object has no attribute '_sindex'`.

```py
import geopandas
import pandas

df = geopandas.read_file(geopandas.datasets.get_path('nybb'))
df.to_pickle('tst.pkl')

pandas.read_pickle('tst.pkl').sindex
```
```py

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-b2cfd76702ae> in <module>
----> 1 pandas.read_pickle('tst.pkl').sindex

/opt/miniconda3/envs/geo_dev/lib/python3.7/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5137             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5138                 return self[name]
-> 5139             return object.__getattribute__(self, name)
   5140 
   5141     def __setattr__(self, name: str, value) -> None:

~/Git/geopandas/martinfleis/geopandas/base.py in sindex(self)
    963     @property
    964     def sindex(self):
--> 965         return self.geometry.values.sindex
    966 
    967     @property

~/Git/geopandas/martinfleis/geopandas/array.py in sindex(self)
    293     @property
    294     def sindex(self):
--> 295         if self._sindex is None:
    296             self._sindex = _get_sindex_class()(self.data)
    297         return self._sindex

AttributeError: 'GeometryArray' object has no attribute '_sindex'
```

I think we need some machinery here as we have for CRS: https://github.com/geopandas/geopandas/blob/1ef924270e950c6e8862335c42ace8d90e5cb3db/geopandas/array.py#L420-L436

There is one related issue with the pickling of `pygeos.STRtree` which currently raises `TypeError: can't pickle pygeos.lib.STRtree objects` so that may need to be resolved before we can properly pickle gdf. 

Anyway, even if sindex will not be pickled, geodataframe read from pickle should be able to build it, which fail atm.

Works in 0.8.1.

### PR DESCRIPTION
**Pull request by martinfleis**
Closes #1745
Closes #1746

Moving conditions into `__setstate__` and `__getstate__` to make sure it reacts to `geopandas.options.use_pygeos = False`.

_edit:_ I have also included a patch for #1746 now. Since `pygeos.STRtree` cannot be pickled now, it is ignored during pickling and `_sindex` is set to `None` during un-pickling.

### CODE REVIEW

File: geopandas/io/tests/test_pickle.py [hunk 1]
```diff
@@ -58,3 +59,18 @@ def test_round_trip_current(tmpdir, current_pickle_data):
...
+    geopandas.options.use_pygeos = False
+    gdf_crs = geopandas.GeoDataFrame(
+        {"a": [0.1, 0.2, 0.3], "geometry": [Point(1, 1), Point(2, 2), Point(3, 3)]},
+        crs="EPSG:4326",
+    )
+    path = str(tmpdir / "{}.pickle".format(gdf_crs))
+    gdf_crs.to_pickle(path)
+    result = pd.read_pickle(path)
+    assert_geodataframe_equal(result, gdf_crs)
+    geopandas.options.use_pygeos = True
```
Comment (martinfleis) [inline geopandas/io/tests/test_pickle.py:76]: For some reason, this switch back to True is not picked on windows (if you remove it the same errors are in all envs). I have no clue why is that and no win machine to debug this. Since this is a super rare combination of factors (and temporary until shapely 2.0), would it be okay to skip this test under windows?

Comment (jorisvandenbossche) [reply geopandas/io/tests/test_pickle.py:76]: Maybe you can try if using a setup/teardown with a fixture helps?

Something like
```
@pytest.fixture
def with_use_pygeos_false():
    orig = geopandas.options.use_pygeos
    geopandas.options.use_pygeos = no orig
    yield
    geopandas.options.use_pygeos = orig
```        

In theory it should do the same, but who knows

**Comment by jorisvandenbossche** [comment]
Thanks!
