### ISSUE TITLE
BUG/COMPAT: missing values handling / fillna no longer working with shapely 1.6

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#509]
See https://github.com/Toblerity/Shapely/issues/510 for more detailed exploration of the problem

Temporarily pinned our CI to older shapely version (but kept one with the latest shapely in the allowed failures section) in https://github.com/geopandas/geopandas/pull/508

**Comment by jorisvandenbossche** [comment]
So we should fix this for 0.3. 
This pops up when you have missing values in the geometry column. Filling the missing values with an empty geometry no longer works. Therefore you get an error "" AttributeError: 'NoneType' object has no attribute 'is_empty' "", because in the operations, we often check if a geom is empty or not before performing the op, eg:

https://github.com/geopandas/geopandas/blob/6dc4ab2cc9f7a6cdffa9d33c8300ff734410a448/geopandas/base.py#L51

So either we also check for nan/None in the above check, or we fix the fillna. To fix fillna, we probably have to broadcast the fill value (empty geometry) to a like-indexed series ourselfves (as it is this step with numpy in the pandas internals that no longer works due to changes in the array interface of empty polygons)
